// Code generated by "stringer -type=ArtifactType -output=artifacts_type_strings.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtifactTypeChatLog-1]
	_ = x[ArtifactTypeCoincidentIPsLog-2]
	_ = x[ArtifactTypeAdminLog-4]
	_ = x[ArtifactTypeBanLog-8]
	_ = x[ArtifactTypeTicketsLog-16]
	_ = x[ArtifactTypeJoinLog-32]
	_ = x[ArtifactTypePlayerProfilesLog-64]
	_ = x[ArtifactPlayerDataErrorsLog-128]
	_ = x[ArtifactTypePythonErrorLog-256]
	_ = x[ArtifactTypePythonLaunchErrorLog-512]
	_ = x[ArtifactTypeBF2Demo-1024]
	_ = x[ArtifactTypePRDemo-2048]
	_ = x[ArtifactTypePRDemoPrivate-4096]
}

const _ArtifactType_name = "ArtifactTypeChatLogArtifactTypeCoincidentIPsLogArtifactTypeAdminLogArtifactTypeBanLogArtifactTypeTicketsLogArtifactTypeJoinLogArtifactTypePlayerProfilesLogArtifactPlayerDataErrorsLogArtifactTypePythonErrorLogArtifactTypePythonLaunchErrorLogArtifactTypeBF2DemoArtifactTypePRDemoArtifactTypePRDemoPrivate"

var _ArtifactType_map = map[ArtifactType]string{
	1:    _ArtifactType_name[0:19],
	2:    _ArtifactType_name[19:47],
	4:    _ArtifactType_name[47:67],
	8:    _ArtifactType_name[67:85],
	16:   _ArtifactType_name[85:107],
	32:   _ArtifactType_name[107:126],
	64:   _ArtifactType_name[126:155],
	128:  _ArtifactType_name[155:182],
	256:  _ArtifactType_name[182:208],
	512:  _ArtifactType_name[208:240],
	1024: _ArtifactType_name[240:259],
	2048: _ArtifactType_name[259:277],
	4096: _ArtifactType_name[277:302],
}

func (i ArtifactType) String() string {
	if str, ok := _ArtifactType_map[i]; ok {
		return str
	}
	return "ArtifactType(" + strconv.FormatInt(int64(i), 10) + ")"
}
