// Code generated by "stringer -type=ArtifactType -linecomment -output=artifact_type_strings.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtifactTypeBF2Demo-1]
	_ = x[ArtifactTypePRDemo-2]
	_ = x[ArtifactTypePRDemoPrivate-4]
	_ = x[ArtifactTypeJSONSummary-8]
}

const (
	_ArtifactType_name_0 = "bf2demoprdemo"
	_ArtifactType_name_1 = "prdemoprivate"
	_ArtifactType_name_2 = "jsonsummary"
)

var (
	_ArtifactType_index_0 = [...]uint8{0, 7, 13}
)

func (i ArtifactType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ArtifactType_name_0[_ArtifactType_index_0[i]:_ArtifactType_index_0[i+1]]
	case i == 4:
		return _ArtifactType_name_1
	case i == 8:
		return _ArtifactType_name_2
	default:
		return "ArtifactType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
