// Code generated by "stringer -type=LogType -linecomment -output=log_type_strings.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogTypeChat-1]
	_ = x[LogTypeCoincidentIPs-2]
	_ = x[LogTypeAdmin-4]
	_ = x[LogTypeBan-8]
	_ = x[LogTypeTickets-16]
	_ = x[LogTypeJoin-32]
	_ = x[LogTypePlayerProfiles-64]
	_ = x[LogTypePlayerDataErrors-128]
	_ = x[LogTypePythonErrors-256]
	_ = x[LogTypePythonLaunchErrors-512]
}

const (
	_LogType_name_0 = "chatlogcoincidentips"
	_LogType_name_1 = "adminlog"
	_LogType_name_2 = "banlog"
	_LogType_name_3 = "tickets"
	_LogType_name_4 = "joinlog"
	_LogType_name_5 = "playerprofiles"
	_LogType_name_6 = "playerdataerrors"
	_LogType_name_7 = "pythonerrors"
	_LogType_name_8 = "pythonlauncherrors"
)

var (
	_LogType_index_0 = [...]uint8{0, 7, 20}
)

func (i LogType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LogType_name_0[_LogType_index_0[i]:_LogType_index_0[i+1]]
	case i == 4:
		return _LogType_name_1
	case i == 8:
		return _LogType_name_2
	case i == 16:
		return _LogType_name_3
	case i == 32:
		return _LogType_name_4
	case i == 64:
		return _LogType_name_5
	case i == 128:
		return _LogType_name_6
	case i == 256:
		return _LogType_name_7
	case i == 512:
		return _LogType_name_8
	default:
		return "LogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
