syntax = "proto3";

option go_package = "github.com/sboon-gg/svctl/svctl";

package svctl;

service Servers {
  rpc Start(ServerOpts) returns (ServerInfo) {}
  rpc Stop(ServerOpts) returns (ServerInfo) {}
  rpc Register(ServerOpts) returns (ServerInfo) {}
  rpc Status(ServerOpts) returns (ServerInfo) {}
  rpc Reset(ServerOpts) returns (ServerInfo) {}
}

message ServerOpts {
  string path = 1;
  string settingsPath = 2;
}

enum Status {
  None = 0;
  REGISTERED = 1;
  STARTING = 2;
  STOPPING = 3;
}

enum State {
  STOPPED = 0;
  RUNNING = 1;
}

message GameStatus {
  string hostname = 1;
  string port = 2;
  string gamemode = 3;
  string map_name = 4;
  int64 map_size = 5;
  int64 num_players = 6;
  int64 max_players = 7;
}

message ServerInfo {
  string path = 1;
  string settingsPath = 2;
  Status status = 3;
  State desired_state = 4;
  State current_state = 5;
  GameStatus game_status = 6;
}
