// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: svctl/v1/svctl.proto

package svctl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Servers_Start_FullMethodName    = "/svctl.v1.Servers/Start"
	Servers_Stop_FullMethodName     = "/svctl.v1.Servers/Stop"
	Servers_Register_FullMethodName = "/svctl.v1.Servers/Register"
	Servers_Status_FullMethodName   = "/svctl.v1.Servers/Status"
	Servers_Reset_FullMethodName    = "/svctl.v1.Servers/Reset"
	Servers_Render_FullMethodName   = "/svctl.v1.Servers/Render"
)

// ServersClient is the client API for Servers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServersClient interface {
	Start(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error)
	Stop(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error)
	Register(ctx context.Context, in *RegisterServerOpts, opts ...grpc.CallOption) (*ServerInfo, error)
	Status(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error)
	Reset(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error)
	Render(ctx context.Context, in *RenderOpts, opts ...grpc.CallOption) (*ServerInfo, error)
}

type serversClient struct {
	cc grpc.ClientConnInterface
}

func NewServersClient(cc grpc.ClientConnInterface) ServersClient {
	return &serversClient{cc}
}

func (c *serversClient) Start(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Start_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) Stop(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Stop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) Register(ctx context.Context, in *RegisterServerOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) Status(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) Reset(ctx context.Context, in *ServerOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Reset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) Render(ctx context.Context, in *RenderOpts, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, Servers_Render_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServersServer is the server API for Servers service.
// All implementations must embed UnimplementedServersServer
// for forward compatibility
type ServersServer interface {
	Start(context.Context, *ServerOpts) (*ServerInfo, error)
	Stop(context.Context, *ServerOpts) (*ServerInfo, error)
	Register(context.Context, *RegisterServerOpts) (*ServerInfo, error)
	Status(context.Context, *ServerOpts) (*ServerInfo, error)
	Reset(context.Context, *ServerOpts) (*ServerInfo, error)
	Render(context.Context, *RenderOpts) (*ServerInfo, error)
	mustEmbedUnimplementedServersServer()
}

// UnimplementedServersServer must be embedded to have forward compatible implementations.
type UnimplementedServersServer struct {
}

func (UnimplementedServersServer) Start(context.Context, *ServerOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedServersServer) Stop(context.Context, *ServerOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedServersServer) Register(context.Context, *RegisterServerOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedServersServer) Status(context.Context, *ServerOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedServersServer) Reset(context.Context, *ServerOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedServersServer) Render(context.Context, *RenderOpts) (*ServerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedServersServer) mustEmbedUnimplementedServersServer() {}

// UnsafeServersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServersServer will
// result in compilation errors.
type UnsafeServersServer interface {
	mustEmbedUnimplementedServersServer()
}

func RegisterServersServer(s grpc.ServiceRegistrar, srv ServersServer) {
	s.RegisterService(&Servers_ServiceDesc, srv)
}

func _Servers_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Start(ctx, req.(*ServerOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Stop(ctx, req.(*ServerOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServerOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Register(ctx, req.(*RegisterServerOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Status(ctx, req.(*ServerOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Reset(ctx, req.(*ServerOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Servers_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).Render(ctx, req.(*RenderOpts))
	}
	return interceptor(ctx, in, info, handler)
}

// Servers_ServiceDesc is the grpc.ServiceDesc for Servers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Servers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svctl.v1.Servers",
	HandlerType: (*ServersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Servers_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Servers_Stop_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Servers_Register_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Servers_Status_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Servers_Reset_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _Servers_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svctl/v1/svctl.proto",
}
